const Users = [
  {
    name: "Anchal Tyagi",
    userName: "anchaltyagi",
    profession: "Full Stack Developer",
    bio: "Building web apps & sharing code insights.",
    img: "https://images.unsplash.com/photo-1534945773093-1119ae5684ab?ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NXx8bGFkeXxlbnwwfDJ8MHx8fDI%3D&auto=format&fit=crop&q=60&w=700",
    followers: 2500,
    posts: 150,
    follows: 300,
  },
  {
    name: "Rohan Sharma",
    userName: "rohan.sharma",
    profession: "Frontend Developer",
    bio: "Crafting seamless UI experiences.",
    img: "https://randomuser.me/api/portraits/men/32.jpg",
    followers: 4200,
    posts: 98,
    follows: 500,
  },
  {
    name: "Sneha Kapoor",
    userName: "sneha.kapoor",
    profession: "UI/UX Designer",
    bio: "Designing intuitive interfaces with love.",
    img: "https://randomuser.me/api/portraits/women/45.jpg",
    followers: 3800,
    posts: 120,
    follows: 460,
  },
  {
    name: "Aditya Verma",
    userName: "aditya_verma",
    profession: "Backend Developer",
    bio: "Making servers work like magic.",
    img: "https://randomuser.me/api/portraits/men/65.jpg",
    followers: 150,
    posts: 10,
    follows: 100,
  },
  {
    name: "Priya Singh",
    userName: "priya_singh",
    profession: "Software Engineer",
    bio: "Passionate about problem solving & algorithms.",
    img: "https://randomuser.me/api/portraits/women/28.jpg",
    followers: 120,
    posts: 8,
    follows: 90,
  },
  {
    name: "Karan Mehta",
    userName: "karanmehta",
    profession: "Data Scientist",
    bio: "Exploring data mysteries one model at a time.",
    img: "https://randomuser.me/api/portraits/men/74.jpg",
    followers: 5400,
    posts: 105,
    follows: 600,
  },
  {
    name: "Anjali Joshi",
    userName: "anjalijoshi",
    profession: "Project Manager",
    bio: "Leading teams to success.",
    img: "https://randomuser.me/api/portraits/women/36.jpg",
    followers: 2200,
    posts: 60,
    follows: 280,
  },
  {
    name: "Siddharth Malhotra",
    userName: "siddharth.m",
    profession: "DevOps Engineer",
    bio: "Bridging dev & ops with automation.",
    img: "https://randomuser.me/api/portraits/men/21.jpg",
    followers: 3300,
    posts: 95,
    follows: 400,
  },
  {
    name: "Nisha Patel",
    userName: "nishapatel",
    profession: "QA Engineer",
    bio: "Breaking to fix bugs.",
    img: "https://randomuser.me/api/portraits/women/55.jpg",
    followers: 180,
    posts: 12,
    follows: 140,
  },
  {
    name: "Vikram Chauhan",
    userName: "vikram.chauhan",
    profession: "Mobile Developer",
    bio: "Coding mobile apps with passion.",
    img: "https://randomuser.me/api/portraits/men/44.jpg",
    followers: 4000,
    posts: 130,
    follows: 520,
  },
];

export default Users;
